//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Football
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameTable
    {
        public int Id { get; set; }
        public int FirstTeam { get; set; }
        public int SecondTeam { get; set; }
        public Nullable<int> FirstTeamScore { get; set; }
        public Nullable<int> SecondTeamScore { get; set; }
    
        public virtual TeamsTable TeamsTable { get; set; }
        public virtual TeamsTable TeamsTable1 { get; set; }
    }
}
