//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Football
{
    using System;
    using System.Collections.Generic;
    
    public partial class teamTable
    {
        public int Nr { get; set; }
        public string Name { get; set; }
        public Nullable<int> Victories { get; set; }
        public Nullable<int> Goals { get; set; }
    }
}
